### ISSUE TITLE
Any plan to update this extention further

### ISSUE THREAD

**Issue by bhupesh-sf** [FlohGro-dev/Craftcuts#10]
Hey there! I'm brand new to craft and stumbled upon this repo while searching for eXtensions. I think it's really awesome! I was wondering if you have any plans to update it with more stuff?

By the way, I have a question about asking for user inputs. I want to import issues from JIRA, but each user will need to enter their own token. How can I accomplish that when creating a new eXtension?

**Comment by FlohGro-dev** [comment]
@bhupesh-sf Thanks for your request.
I don't have any plans to update the extension. It's also mentioned in the readme.

Craft basically has abandoned extensions since 1.5 years so I don't think they will come back anytime soon (especially not with the same API)

**Comment by bhupesh-sf** [comment]
Any reason they have abandoned extensions as those are the most powerful way to extend it?

**Comment by FlohGro-dev** [comment]
I think their strategy changed towards a more team focused approach with collaboration first.

The API was not powerful enough. I provided a lot of feedback to improve it and first they wanted to rework and relaunch it but that never happened.

**Comment by bhupesh-sf** [comment]
is there a way we can connect with them as a community and try to push them to move ahead with this approach? Tasks is one area that really needs improvements and I think these plugins can really help them.

**Comment by FlohGro-dev** [comment]
You can try it here: https://community.craft.do/home

You're not the first one though.

I'll close this issue for now :)
